version: "3"

services:
  service:
    image: dorinbotan/docker_autobuild
    volumes:
      - "test:/root"
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - "test:/test"
    command: [ "/root/test.sh", "0" ]

volumes:
  test:
